
executable = /bin/bash
arguments = RHL466_hair_p50_sample.sh
# LOGS
error  = ../logs_condor/$(ClusterId).$(ProcId)_20_hair_p50_sample.err
output = ../logs_condor/$(ClusterId).$(ProcId)_20_hair_p50_sample.out
log    = ../logs_condor/$(ClusterId).$(ProcId)_20_hair_p50_sample.log

request_cpus = 10
request_gpus = 1
requirements = (TARGET.CUDADeviceName == "NVIDIA A100-SXM4-80GB") && (UtsnameNodename =!= "g156") && (UtsnameNodename =!= "g121") && (UtsnameNodename =!= "g164")
request_memory = 131072
queue
